
apiVersion: v1
kind: ConfigMap
metadata:
  name: flekszible-operator
data:
  Flekszible: |+
    source:
    - url: github.com/flokkr/docker-ozone
    import:
    - path: ozone-client
    transformations:
      - type: ozone/ozonefs
        image: elek/ozone-dev:1326aaa45
        trigger:
           metadata:
              annotations:
                 ozonefs: enable
      - type: ozone/client-config
        trigger:
           metadata:
              annotations:
                 ozonefs: enable

