
apiVersion: v1
kind: ConfigMap
metadata:
  name: flekszible-operator
data:
  Flekszible: |+
    transformations:
      - type: Add
        path:
          - metadata
          - labels
        value:
          generated: "true"

