#!/usr/bin/env bash



test(){
   go test ./...
   cd api
   go test ./...
}

build(){
   go install ./...
}

release(){
   goreleaser release  --rm-dist
}

if [ ! "$@" ]; then
    echo "Available targets"
    declare -F | awk '{print $3}'
else
   "$@"
fi
