apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: descriptors.flekszible.github.io
spec:
  group: flekszible.github.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: descriptors
    singular: descriptor
    kind: Descriptor
    shortNames:
    - fksz
