
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      version: 1
      editable: false
