version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/flekszible
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: ./build 
      - run:
          name: Run unit tests
          command: |
              ./build test
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
