on: push
name: build
jobs:
  build-linux:
    name: Go Test Linux
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.19.5’
    - uses: actions/checkout@master
    - name: build
      run: |
          ./build build
    - name: unit tests
      run: |
          ./build test
  build-osx:
    name: Go Test OSX
    runs-on: macos-12
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.19.5’
    - uses: actions/checkout@master
    - name: build
      run: |
          ./build build
    - name: unit tests
      run: |
          ./build test
